
export const REGISTER_NEW = "REGISTER_NEW";

export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const VISIBLE_ALL = 'VISIBLE_ALL';
export const VISIBLE_REGISTERED = 'VISIBLE_REGISTERED';
export const VISIBLE_DELETED = 'VISIBLE_DELETED';
